### ISSUE TITLE
Review documentation in the readme

### ISSUE THREAD

**Issue by briancroxall** [briancroxall/borderwaters#3]
Does the [readme](https://github.com/briancroxall/borderwaters/blob/master/README.md) for this repo do an adequate job with the following:

- [x] describing the contents of the repo
- [x] describing the processes that were undertaken in the research

**Comment by rlskoeser** [comment]
I was able to follow the readme, understand the repository organization, find referenced scripts and data files, and understand the processes taken in sequence for the research. I appreciate the care in documenting and detailing the work taken and the approach.

The readme, repository structure, scripts and data seem entirely sufficient for your goals.

Based on reviewing the readme and the rest of the repository, I have some suggestions that may improve the documentation. 
- The first time I saw it (Data.3), I wasn't immediately sure what "hand-downloads" meant. Somehow it sounded like a technical term; I presume this means that files were manually downloaded, and I saw later that you use the term elsewhere throughout. Perhaps you could add a gloss to clarify the first term it occurs.
- I recommend depositing this repository with Zenodo and generating a DOI for the repository citation.  See https://guides.github.com/activities/citable-code/ for specifics. Zenodo metadata will also allow you to specify relationships between this object and others, i.e. the _Borderwaters_ book.  
- For the citation as currently listed — I wasn't sure if the italics in citation were as intended, it looks a little strange to me (but I'm not familiar MLA citation format for resources like this).
- Consider using relative links from the readme to the referenced folders, to make it easier for people reading the documentation to acesss the folders. See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-readmes#relative-links-and-image-paths-in-readme-files
- In the data collection section, you note HTML format for manual downloads but don't specify format for others; could be clarified
- In the analysis section, you mention normed images, but I only see the raw versions in the repository; I see this is explained in the bolded section immediately following, but it could be a clearer. Perhaps the bolded section should _start_ with the fact that only the results you ended up using are in the repository, and then explain why; I would also recommend that whole paragraph not be bold. 
- Consider renaming repository default branch from master to main. For context and instructions, see the slave/master  section of this document: https://ach.org/toward-anti-racist-technical-terminology/
- I didn't look closely at the scripts, but noticed that some of them include dependencies beyond the standard python library (i.e., BeautifulSoup). I recommend you document somewhere (per script or repository wide) the python dependencies that need to be installed to run these scripts. And even though your goal is not full reproducibility (due to the source limitations), I would also recommend documenting the version of python and versions of python libraries that you used (if you are still able to generate that information). If you were working in a python virtual environment with pip, you can use `pip freeze` to generate a list of dependencies and versions; that could simply be added to the repository as a text file.

**Comment by briancroxall** [comment]
To-dos

- [x] clarify hand-download
- [x] double-check citation italics
- [x] use relative links in readme to referenced folders
- [x] clarify formats in Data collection section
- [x] deal with bolded paragraph in the analysis section
- [x] rename default branch from `master` to `main`
- [x] include dependencies
- [x] deposit repository with Zenodo
- [ ] document versions of python and its libraries that were used in development

**Comment by briancroxall** [comment]
I'm afraid that I'm not a good enough developer to have thought to use virtual environments for any of this work. As such, my environment has changed a lot in the three years that I've been working on this, and I won't be able to document which versions of the different libraries I've been using.

**Comment by rlskoeser** [comment]
@briancroxall even "good" developers and researchers don't always keep track of that! If you don't know, don't worry about it. Maybe just a brief note that the work was done across multiple machines over multiple years and particular versions of dependencies were not tracked. (If you at least know the approximate version of python it might be worth noting.)

**Comment by briancroxall** [comment]
Good suggestion. I've implemented it as best as I could.
